name: Merge to Staging and main branches

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      ENVIRONMENT_NAME:
        description: "The environment to use in running the workflow (Staging or Production)"
        required: true 
        type: string
      TERRAFORM_VERSION:
        description: " The Terraform version to be installed on the runner"
        required: true 
        type: string
      TERRAGRUNT_VERSION:
        description: "The Terragrunt version to be installed on the runner"
        required: true 
        type: string
      TERRAFORM_WORKING_DIR:
        required: true 
        type: string
      AWS_REGION:
        required: true 
        type: string
      ORCHESTRATION_ROLE_ARN:
        required: true 
        type: string
    #secrets:
     # AWS_ACCESS_KEY_ID:
      #  required: true 
      #AWS_SECRET_ACCESS_KEY:
       # required: true

jobs:
  apply:
    name: "Run apply in Staging and Production environment"
    environment: ${{ inputs.ENVIRONMENT_NAME }}
    runs-on: ubuntu-20.04
    defaults:
       run:
        working-directory: ${{ inputs.TERRAFORM_WORKING_DIR }}
    steps:
      - name: 'checkout'   
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: ${{ inputs.TERRAFORM_VERSION }} 
          terraform_wrapper: true

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: ${{ inputs.TERRAGRUNT_VERSION }}

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with: 
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ inputs.ORCHESTRATION_ROLE_ARN }}
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terragrunt Init
        id: init
        run: terragrunt run-all init -no-color --terragrunt-non-interactive

      - name: Terragrunt Apply
        id: plan
        run: terragrunt run-all apply -no-color --terragrunt-non-interactive
